/** Static list of nations for the marquee component */
export const MARQUEE_NATIONS = [
  { code: 'ar', key: 'ar' },
  { code: 'br', key: 'br' },
  { code: 'fr', key: 'fr' },
  { code: 'de', key: 'de' },
  { code: 'es', key: 'es' },
  { code: 'uy', key: 'uy' },
  { code: 'it', key: 'it' },
  { code: 'gb-eng', key: 'eng' },
  { code: 'us', key: 'us' },
  { code: 'mx', key: 'mx' },
  { code: 'jp', key: 'jp' },
  { code: 'kr', key: 'kr' },
  { code: 'ma', key: 'ma' },
  { code: 'hr', key: 'hr' },
  { code: 'nl', key: 'nl' },
  { code: 'pt', key: 'pt' },
  { code: 'be', key: 'be' },
  { code: 'ch', key: 'ch' },
  { code: 'dk', key: 'dk' },
  { code: 'sn', key: 'sn' },
  { code: 'co', key: 'co' },
  { code: 'cl', key: 'cl' },
  { code: 'ec', key: 'ec' },
  { code: 'ca', key: 'ca' },
  { code: 'au', key: 'au' },
  { code: 'gh', key: 'gh' },
  { code: 'cm', key: 'cm' },
  { code: 'sa', key: 'sa' },
  { code: 'pl', key: 'pl' },
  { code: 'se', key: 'se' },
  { code: 'rs', key: 'rs' },
  { code: 'tn', key: 'tn' },
] as const
