/** Static list of nations for the marquee component */
export const MARQUEE_NATIONS = [
  { code: 'mx', key: 'mx' }, { code: 'za', key: 'za' },
  { code: 'kr', key: 'kr' }, { code: 'cz', key: 'cz' },
  { code: 'ca', key: 'ca' }, { code: 'ba', key: 'ba' },
  { code: 'qa', key: 'qa' }, { code: 'ch', key: 'ch' },
  { code: 'br', key: 'br' }, { code: 'ma', key: 'ma' },
  { code: 'ht', key: 'ht' }, { code: 'gb-sct', key: 'sct' },
  { code: 'us', key: 'us' }, { code: 'py', key: 'py' },
  { code: 'au', key: 'au' }, { code: 'tr', key: 'tr' },
  { code: 'de', key: 'de' }, { code: 'cw', key: 'cw' },
  { code: 'ci', key: 'ci' }, { code: 'ec', key: 'ec' },
  { code: 'nl', key: 'nl' }, { code: 'jp', key: 'jp' },
  { code: 'se', key: 'se' }, { code: 'tn', key: 'tn' },
  { code: 'be', key: 'be' }, { code: 'eg', key: 'eg' },
  { code: 'ir', key: 'ir' }, { code: 'nz', key: 'nz' },
  { code: 'es', key: 'es' }, { code: 'cv', key: 'cv' },
  { code: 'sa', key: 'sa' }, { code: 'uy', key: 'uy' },
  { code: 'fr', key: 'fr' }, { code: 'sn', key: 'sn' },
  { code: 'iq', key: 'iq' }, { code: 'no', key: 'no' },
  { code: 'ar', key: 'ar' }, { code: 'dz', key: 'dz' },
  { code: 'at', key: 'at' }, { code: 'jo', key: 'jo' },
  { code: 'pt', key: 'pt' }, { code: 'cd', key: 'cd' },
  { code: 'uz', key: 'uz' }, { code: 'co', key: 'co' },
  { code: 'gb-eng', key: 'eng' }, { code: 'hr', key: 'hr' },
  { code: 'gh', key: 'gh' }, { code: 'pa', key: 'pa' },
] as const
